channels:
  - conda-forge
dependencies:
  - python=3.9.19
  - pip=24.3.1
  - pip:
      - mltable==1.6.3
      - mlflow-skinny==2.7.1
      - azureml-mlflow==1.48.0
      - numpy==1.26.4
      - pandas==1.5.3
      - scikit-learn==1.4.2
      - scipy==1.11.4
      - azureml-inference-server-http==0.8.0
name: admissions_env